# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 14:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import gestion.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaFormacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('asistencia', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Becario',
            fields=[
                ('nombre', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^(?i)([a-z\xf1\xc1\xc9\xcd\xd3\xda\xe1\xe9\xed\xf3\xfa. ]{2,60})$')])),
                ('apellido1', models.CharField(max_length=200)),
                ('apellido2', models.CharField(blank=True, max_length=200)),
                ('orden', models.PositiveIntegerField(unique=True)),
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[gestion.models.dni_validator])),
                ('estado', models.CharField(choices=[('A', 'Asignado'), ('S', 'Suplente'), ('R', 'Renuncia'), ('E', 'Excluido'), ('N', 'No asignado')], default='N', max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.PositiveIntegerField(blank=True, null=True, validators=[gestion.models.telefono_validator])),
                ('permisos', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CambiosPendientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateField(blank=True, null=True)),
                ('estado_cambio', models.CharField(choices=[('A', 'Asignado'), ('R', 'Renuncia'), ('T', 'Traslado')], max_length=1)),
                ('observaciones', models.TextField(blank=True)),
                ('becario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Becario')),
            ],
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anyo_inicio', models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034), (2035, 2035)], default=2016)),
                ('anyo_fin', models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034), (2035, 2035)], default=2017)),
            ],
        ),
        migrations.CreateModel(
            name='Emplazamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialBecarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_becario', models.CharField(max_length=8, validators=[gestion.models.dni_validator])),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('fecha_renuncia', models.DateField(blank=True, null=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.Convocatoria')),
            ],
        ),
        migrations.CreateModel(
            name='PlanFormacion',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=200)),
                ('lugar_imparticion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_imparticion', models.DateTimeField(blank=True, null=True)),
                ('asistentes', models.ManyToManyField(through='gestion.AsistenciaFormacion', to='gestion.Becario')),
            ],
        ),
        migrations.CreateModel(
            name='Plaza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(choices=[('M', 'Ma\xf1ana'), ('T', 'Tarde')], max_length=1)),
                ('emplazamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Emplazamiento')),
            ],
        ),
        migrations.CreateModel(
            name='PreferenciasBecario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_orden', models.PositiveSmallIntegerField()),
                ('becario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Becario')),
                ('plaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Plaza')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableAula',
            fields=[
                ('nombre', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^(?i)([a-z\xf1\xc1\xc9\xcd\xd3\xda\xe1\xe9\xed\xf3\xfa. ]{2,60})$')])),
                ('apellido1', models.CharField(max_length=200)),
                ('apellido2', models.CharField(blank=True, max_length=200)),
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[gestion.models.dni_validator])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.PositiveIntegerField(blank=True, null=True, validators=[gestion.models.telefono_validator])),
                ('emplazamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Emplazamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Titulacion',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False, validators=[gestion.models.codigo_tit_validator])),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='convocatoria',
            unique_together=set([('anyo_inicio', 'anyo_fin')]),
        ),
        migrations.AddField(
            model_name='cambiospendientes',
            name='plaza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.Plaza'),
        ),
        migrations.AddField(
            model_name='becario',
            name='plaza_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.Plaza', unique=True),
        ),
        migrations.AddField(
            model_name='becario',
            name='titulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.Titulacion'),
        ),
        migrations.AddField(
            model_name='asistenciaformacion',
            name='becario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Becario'),
        ),
        migrations.AddField(
            model_name='asistenciaformacion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.PlanFormacion'),
        ),
        migrations.AlterUniqueTogether(
            name='preferenciasbecario',
            unique_together=set([('becario', 'plaza'), ('becario', 'num_orden')]),
        ),
        migrations.AlterUniqueTogether(
            name='historialbecarios',
            unique_together=set([('dni_becario', 'convocatoria')]),
        ),
        migrations.AlterUniqueTogether(
            name='cambiospendientes',
            unique_together=set([('becario', 'plaza', 'fecha_cambio')]),
        ),
        migrations.AlterUniqueTogether(
            name='asistenciaformacion',
            unique_together=set([('becario', 'curso')]),
        ),
    ]
