# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='becario',
            name='permisos',
            field=models.BooleanField(default=False),
        ),
    ]
