# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_becario_permisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becario',
            name='plaza_asignada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.Plaza'),
        ),
    ]
