# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_becario_orden'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Centro',
            new_name='Emplazamiento',
        ),
        migrations.RenameField(
            model_name='plaza',
            old_name='centro',
            new_name='emplazamiento',
        ),
        migrations.RenameField(
            model_name='responsableaula',
            old_name='centro',
            new_name='emplazamiento',
        ),
    ]
