# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20161130_1100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrelacionBecario',
            new_name='PreferenciasBecario',
        ),
    ]
