# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20161114_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='prelacionbecario',
            name='num_orden',
            field=models.PositiveSmallIntegerField(default=12),
            preserve_default=False,
        ),
    ]
