# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20161115_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becario',
            name='plaza_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.Plaza', unique=True),
        ),
    ]
