# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_prelacionbecario_num_orden'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prelacionbecario',
            unique_together=set([('becario', 'plaza'), ('becario', 'num_orden')]),
        ),
    ]
