# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20161118_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='becario',
            name='horario_asignado',
        ),
    ]
