# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_becario_horario_asignado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titulacion',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='becario',
            name='titulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.Titulacion'),
        ),
    ]
