# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import gestion.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_auto_20161122_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulacion',
            name='codigo',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, validators=[gestion.models.codigo_tit_validator]),
        ),
    ]
