# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 13:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_auto_20161114_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaFormacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('becario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Becario')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.PlanFormacion')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='asistenciaformacion',
            unique_together=set([('becario', 'curso')]),
        ),
    ]
