# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_responsableaula'),
    ]

    operations = [
        migrations.CreateModel(
            name='CambiosPendientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateField()),
                ('estado_cambio', models.CharField(choices=[('A', 'Asignado'), ('R', 'Renuncia'), ('T', 'Traslado')], max_length=1)),
                ('becario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Becario')),
                ('plaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Plaza')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cambiospendientes',
            unique_together=set([('becario', 'plaza', 'fecha_cambio')]),
        ),
    ]
