# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_auto_20161205_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciaformacion',
            name='asistencia',
            field=models.BooleanField(default=False),
        ),
    ]
