# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_asistenciaformacion_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialbecarios',
            name='fecha_renuncia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
