# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_auto_20161212_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='becario',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cambiospendientes',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cambiospendientes',
            name='fecha_cambio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cambiospendientes',
            name='plaza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.Plaza'),
        ),
    ]
