# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_convocatoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialbecarios',
            name='convocatoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='gestion.Convocatoria'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='historialbecarios',
            name='anyo',
        ),
        migrations.AlterUniqueTogether(
            name='historialbecarios',
            unique_together=set([('dni_becario', 'convocatoria')]),
        ),
    ]
