# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_auto_20161219_1341'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='convocatoria',
            unique_together=set([('anyo_inicio', 'anyo_fin')]),
        ),
    ]
